"""google image

Revision ID: 67e3a3262a8a
Revises: 
Create Date: 2026-05-15 19:25:51.823928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67e3a3262a8a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matchbvdid')
    op.drop_table('orgdata')
    op.add_column('address_zone_master', sa.Column('image_name', sa.String(length=255), nullable=True))
    op.alter_column('address_zone_master', 'geocode_status',
               existing_type=postgresql.ENUM('not_called', 'failed', 'passed', name='step_status_enum'),
               type_=sa.Enum('not_called', 'failed', 'passed', name='step_status_enum', schema='public'),
               existing_nullable=True)
    op.alter_column('address_zone_master', 'places_status',
               existing_type=postgresql.ENUM('not_called', 'failed', 'passed', name='step_status_enum'),
               type_=sa.Enum('not_called', 'failed', 'passed', name='step_status_enum', schema='public'),
               existing_nullable=True)
    op.alter_column('address_zone_master', 'llm_status',
               existing_type=postgresql.ENUM('not_called', 'failed', 'passed', name='step_status_enum'),
               type_=sa.Enum('not_called', 'failed', 'passed', name='step_status_enum', schema='public'),
               existing_nullable=True)
    op.alter_column('address_zone_master', 'geocode_source',
               existing_type=postgresql.ENUM('not_called', 'google', 'llm', name='geocode_source_enum'),
               type_=sa.Enum('not_called', 'google', 'llm', name='geocode_source_enum', schema='public'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('address_zone_master', 'geocode_source',
               existing_type=sa.Enum('not_called', 'google', 'llm', name='geocode_source_enum', schema='public'),
               type_=postgresql.ENUM('not_called', 'google', 'llm', name='geocode_source_enum'),
               existing_nullable=True)
    op.alter_column('address_zone_master', 'llm_status',
               existing_type=sa.Enum('not_called', 'failed', 'passed', name='step_status_enum', schema='public'),
               type_=postgresql.ENUM('not_called', 'failed', 'passed', name='step_status_enum'),
               existing_nullable=True)
    op.alter_column('address_zone_master', 'places_status',
               existing_type=sa.Enum('not_called', 'failed', 'passed', name='step_status_enum', schema='public'),
               type_=postgresql.ENUM('not_called', 'failed', 'passed', name='step_status_enum'),
               existing_nullable=True)
    op.alter_column('address_zone_master', 'geocode_status',
               existing_type=sa.Enum('not_called', 'failed', 'passed', name='step_status_enum', schema='public'),
               type_=postgresql.ENUM('not_called', 'failed', 'passed', name='step_status_enum'),
               existing_nullable=True)
    op.drop_column('address_zone_master', 'image_name')
    op.create_table('orgdata',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('orgname', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('orgidentifier', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('bvdids', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('orgdata_pkey')),
    sa.UniqueConstraint('bvdids', name=op.f('orgdata_bvdids_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('orgidentifier', name=op.f('orgdata_orgidentifier_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('matchbvdid',
    sa.Column('bvdid', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name_international', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('postcode', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone_or_fax', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email_or_website', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('national_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('address_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ens_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ens_id', name=op.f('matchbvdid_pkey'))
    )
    # ### end Alembic commands ###
